"""Add winner_id to targets

Revision ID: 0f69675582e6
Revises: 3060a51317a2
Create Date: 2026-05-31 02:08:25.662410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f69675582e6'
down_revision = '3060a51317a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Focus only on adding the winner_id to targets
    op.add_column('targets', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_targets_winner_id'), 'targets', ['winner_id'], unique=False)
    op.create_foreign_key('fk_targets_winner_user', 'targets', 'users', ['winner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_targets_winner_user', 'targets', type_='foreignkey')
    op.drop_index(op.f('ix_targets_winner_id'), table_name='targets')
    op.drop_column('targets', 'winner_id')
    # ### end Alembic commands ###
