"""Add candidate roles table and link to candidates

Revision ID: 3eae9dedd70a
Revises: 007
Create Date: 2026-05-24 17:33:30.984512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eae9dedd70a'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_candidates_role_id'), 'candidates', ['role_id'], unique=False)
    op.create_foreign_key(None, 'candidates', 'candidate_roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_role_id'), table_name='candidates')
    op.drop_column('candidates', 'role_id')
    # ### end Alembic commands ###
