"""Add candidate roles table and link to candidates

Revision ID: 3eae9dedd70a
Revises: 007
Create Date: 2026-05-24 17:33:30.984512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eae9dedd70a'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the candidate_roles table first (it was missing from this migration)
    op.create_table(
        'candidate_roles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_roles_id'), 'candidate_roles', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_roles_tenant_id'), 'candidate_roles', ['tenant_id'], unique=False)

    op.add_column('candidates', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_candidates_role_id'), 'candidates', ['role_id'], unique=False)
    op.create_foreign_key('candidates_ibfk_3', 'candidates', 'candidate_roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('candidates_ibfk_3', 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_role_id'), table_name='candidates')
    op.drop_column('candidates', 'role_id')
    op.drop_index(op.f('ix_candidate_roles_tenant_id'), table_name='candidate_roles')
    op.drop_index(op.f('ix_candidate_roles_id'), table_name='candidate_roles')
    op.drop_table('candidate_roles')
    # ### end Alembic commands ###