"""Expand candidate details for nomination

Revision ID: 4008e83140c8
Revises: 0f69675582e6
Create Date: 2026-05-31 02:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4008e83140c8'
down_revision = '0f69675582e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('candidates', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('date_of_birth', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('parent_name', sa.String(length=150), nullable=True))
    op.add_column('candidates', sa.Column('kyc_type', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('voter_id_number', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('taluka', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('village', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('pincode', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('is_willing', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('held_previously', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('prev_position', sa.String(length=150), nullable=True))
    op.add_column('candidates', sa.Column('prev_duration', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('is_disciplined', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('discipline_details', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('has_complaints', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('agreed_constitution', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('accepted_results', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('signature_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'signature_url')
    op.drop_column('candidates', 'accepted_results')
    op.drop_column('candidates', 'agreed_constitution')
    op.drop_column('candidates', 'has_complaints')
    op.drop_column('candidates', 'discipline_details')
    op.drop_column('candidates', 'is_disciplined')
    op.drop_column('candidates', 'prev_duration')
    op.drop_column('candidates', 'prev_position')
    op.drop_column('candidates', 'held_previously')
    op.drop_column('candidates', 'is_willing')
    op.drop_column('candidates', 'pincode')
    op.drop_column('candidates', 'village')
    op.drop_column('candidates', 'taluka')
    op.drop_column('candidates', 'district')
    op.drop_column('candidates', 'state')
    op.drop_column('candidates', 'voter_id_number')
    op.drop_column('candidates', 'kyc_type')
    op.drop_column('candidates', 'parent_name')
    op.drop_column('candidates', 'gender')
    op.drop_column('candidates', 'date_of_birth')
    op.drop_column('candidates', 'phone')
    op.drop_column('candidates', 'email')
    # ### end Alembic commands ###
