"""Add events and event_notifications tables

Revision ID: 40615694a47a
Revises: ac5282656fd4
Create Date: 2026-06-10 14:21:15.826450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40615694a47a'
down_revision = 'ac5282656fd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_date', sa.String(length=50), nullable=False),
    sa.Column('event_time', sa.String(length=50), nullable=False),
    sa.Column('place', sa.String(length=255), nullable=False),
    sa.Column('communication_type', sa.Enum('online', 'offline', name='event_communication_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_by'), 'events', ['created_by'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_table('event_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_notifications_event_id'), 'event_notifications', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_notifications_id'), 'event_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_event_notifications_user_id'), 'event_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_notifications_user_id'), table_name='event_notifications')
    op.drop_index(op.f('ix_event_notifications_id'), table_name='event_notifications')
    op.drop_index(op.f('ix_event_notifications_event_id'), table_name='event_notifications')
    op.drop_table('event_notifications')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_by'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
