"""add_tenant_uuid

Revision ID: 6a4f4f4be64f
Revises: ca2ba2a6e465
Create Date: 2026-05-30 18:06:24.049360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4f4f4be64f'
down_revision = 'ca2ba2a6e465'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('uuid', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tenants_uuid'), 'tenants', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_uuid'), table_name='tenants')
    op.drop_column('tenants', 'uuid')
    # ### end Alembic commands ###
