"""expand_user_for_multi_step_registration

Revision ID: ca2ba2a6e465
Revises: a1b2c3d4e5f6
Create Date: 2026-05-30 16:56:37.336002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca2ba2a6e465'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the plans table if it doesn't exist (it was missing from migrations)
    op.create_table(
        'plans',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('price', sa.Float(), nullable=False, server_default='0'),
        sa.Column('currency', sa.String(length=3), nullable=False, server_default='INR'),
        sa.Column('period', sa.String(length=20), nullable=False, server_default='month'),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('features', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
        sa.Column('is_highlighted', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_tenant_id'), 'plans', ['tenant_id'], unique=False)

    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('parent_name', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('kyc_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('kyc_front_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('kyc_back_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('house_number', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('village', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('landmark', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('taluka', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('current_street_address', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('current_city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('current_district', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('current_state', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('current_pincode', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('committee_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('membership_plan_id', sa.Integer(), nullable=True))
    
    # Date of birth was a string in the model but maybe a Date in DB? 
    # The autogenerate detected a change. Let's keep it safe.
    try:
        op.alter_column('users', 'date_of_birth',
                   existing_type=sa.DATE(),
                   type_=sa.String(length=20),
                   existing_nullable=True)
    except:
        pass

    try:
        op.alter_column('users', 'voter_id',
                   existing_type=mysql.VARCHAR(length=255),
                   type_=sa.String(length=50),
                   existing_nullable=True)
    except:
        pass

    op.create_index(op.f('ix_users_committee_id'), 'users', ['committee_id'], unique=False)
    op.create_index(op.f('ix_users_membership_plan_id'), 'users', ['membership_plan_id'], unique=False)
    
    try:
        op.create_index(op.f('ix_users_voter_id'), 'users', ['voter_id'], unique=True)
    except:
        pass

    op.create_foreign_key('fk_users_plans', 'users', 'plans', ['membership_plan_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_committees', 'users', 'candidate_committees', ['committee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_committees', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_plans', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_voter_id'), table_name='users')
    op.drop_index(op.f('ix_users_membership_plan_id'), table_name='users')
    op.drop_index(op.f('ix_users_committee_id'), table_name='users')
    op.drop_column('users', 'membership_plan_id')
    op.drop_column('users', 'committee_id')
    op.drop_column('users', 'current_pincode')
    op.drop_column('users', 'current_state')
    op.drop_column('users', 'current_district')
    op.drop_column('users', 'current_city')
    op.drop_column('users', 'current_street_address')
    op.drop_column('users', 'taluka')
    op.drop_column('users', 'landmark')
    op.drop_column('users', 'village')
    op.drop_column('users', 'house_number')
    op.drop_column('users', 'kyc_back_url')
    op.drop_column('users', 'kyc_front_url')
    op.drop_column('users', 'kyc_type')
    op.drop_column('users', 'parent_name')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
