"""Add geographical targets entity and link to elections candidates and users

Revision ID: e74e89c267f5
Revises: 6a4239f0d29d
Create Date: 2026-05-24 18:26:07.538134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74e89c267f5'
down_revision = '6a4239f0d29d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('state', 'district', 'zone', 'ward', 'other', name='target_type_enum'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['targets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_id'), 'targets', ['id'], unique=False)
    op.create_index(op.f('ix_targets_parent_id'), 'targets', ['parent_id'], unique=False)
    op.create_index(op.f('ix_targets_tenant_id'), 'targets', ['tenant_id'], unique=False)
    op.add_column('candidates', sa.Column('target_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_candidates_target_id'), 'candidates', ['target_id'], unique=False)
    op.create_foreign_key(None, 'candidates', 'targets', ['target_id'], ['id'], ondelete='SET NULL')
    op.add_column('elections', sa.Column('target_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_elections_target_id'), 'elections', ['target_id'], unique=False)
    op.create_foreign_key(None, 'elections', 'targets', ['target_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('target_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_target_id'), 'users', ['target_id'], unique=False)
    op.create_foreign_key(None, 'users', 'targets', ['target_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_target_id'), table_name='users')
    op.drop_column('users', 'target_id')
    op.drop_constraint(None, 'elections', type_='foreignkey')
    op.drop_index(op.f('ix_elections_target_id'), table_name='elections')
    op.drop_column('elections', 'target_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_target_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_committee_id'), table_name='candidates')
    op.create_index('ix_candidates_role_id', 'candidates', ['committee_id'], unique=False)
    op.drop_column('candidates', 'target_id')
    op.drop_index(op.f('ix_candidate_committees_tenant_id'), table_name='candidate_committees')
    op.drop_index(op.f('ix_candidate_committees_id'), table_name='candidate_committees')
    op.create_index('ix_candidate_roles_tenant_id', 'candidate_committees', ['tenant_id'], unique=False)
    op.create_index('ix_candidate_roles_id', 'candidate_committees', ['id'], unique=False)
    op.drop_index(op.f('ix_targets_tenant_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_parent_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_id'), table_name='targets')
    op.drop_table('targets')
    # ### end Alembic commands ###
